//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace payrol.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class salary
    {
        public int Id { get; set; }
        public Nullable<int> eid { get; set; }
        public Nullable<int> bonus { get; set; }
        public Nullable<int> days { get; set; }
        public Nullable<int> deduction { get; set; }
        public Nullable<System.DateTime> month { get; set; }
    }
}
